[package]
name = "bartholomew"
version = "0.2.0"
edition = "2021"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]

[dependencies]
anyhow = "1.0"
chrono = {version = "0.4", features = ["serde"]}
flate2 = "1.0"
handlebars = {version = "4.1", features = ["dir_source", "script_helper"]}
handlebars_sprig = { version = "0.2.0" }
pulldown-cmark = { version = "0.8", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"

[workspace]
members = ["bart"]
