name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          rustup target add wasm32-wasi

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test